/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author kyuza
 */
public class FormGaji extends javax.swing.JInternalFrame {
    private final DefaultTableModel gajiDefaultTableModel;
    private final GajiController gajiController = new GajiController();
    
    /**
     * Creates new form FormGaji
     */
    public FormGaji() {
        initComponents();
        
        gajiDefaultTableModel = (DefaultTableModel) gajiTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pekerjaanPopupMenu = new javax.swing.JPopupMenu();
        tambahMenuItem = new javax.swing.JMenuItem();
        hapusMenuItem = new javax.swing.JMenuItem();
        ktpLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        ruangLabel = new javax.swing.JLabel();
        gajiLabel = new javax.swing.JLabel();
        ktpTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        ruangTextField = new javax.swing.JTextField();
        lihatButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        tutupButton = new javax.swing.JButton();
        gajiPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gajiTable = new javax.swing.JTable();

        tambahMenuItem.setText("jMenuItem1");
        tambahMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMenuItemActionPerformed(evt);
            }
        });
        pekerjaanPopupMenu.add(tambahMenuItem);

        hapusMenuItem.setText("jMenuItem2");
        hapusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusMenuItemActionPerformed(evt);
            }
        });
        pekerjaanPopupMenu.add(hapusMenuItem);

        setTitle("Mengelola Gaji Karyawan");

        ktpLabel.setText("KTP");

        namaLabel.setText("Nama");

        ruangLabel.setText("Ruang");

        gajiLabel.setText("Gaji");

        ktpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ktpTextFieldKeyPressed(evt);
            }
        });

        lihatButton.setText("Lihat");
        lihatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        tutupButton.setText("Tutup");

        gajiPanel.setBackground(new java.awt.Color(255, 204, 204));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseReleased(evt);
            }
        });

        gajiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Pekerjaan", "Gaji Bersih", "Gaji Kotor", "Tunjangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gajiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gajiTableMouseReleased(evt);
            }
        });
        gajiTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                gajiTablePropertyChange(evt);
            }
        });
        gajiTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gajiTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(gajiTable);

        javax.swing.GroupLayout gajiPanelLayout = new javax.swing.GroupLayout(gajiPanel);
        gajiPanel.setLayout(gajiPanelLayout);
        gajiPanelLayout.setHorizontalGroup(
            gajiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gajiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        gajiPanelLayout.setVerticalGroup(
            gajiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gajiPanelLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaLabel)
                            .addComponent(ktpLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ktpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lihatButton))
                            .addComponent(namaTextField))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(ruangLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ruangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(simpanButton))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tutupButton)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gajiLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gajiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ktpLabel)
                    .addComponent(ktpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihatButton)
                    .addComponent(ruangLabel)
                    .addComponent(ruangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutupButton))
                .addGap(18, 18, 18)
                .addComponent(gajiLabel)
                .addGap(10, 10, 10)
                .addComponent(gajiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setKtp(String ktp) {
        ktpTextField.setText(ktp);
    }
    
    public void setNama(String nama) {
        ktpTextField.setText(nama);
    }
    
    public void setRuang(String ruang) {
        ktpTextField.setText(ruang);
    }
    
    public void setNamaPekerjaan(String nama) {
        gajiTable.setValueAt(nama, gajiTable.getSelectedColumn(), 1);
    }
    
    public void hapusGaji() {
        for (int i=2; i<=4; i++) {
            gajiTable.setValueAt("", gajiTable.getSelectedRow(), i);
        }
    }
    
    public void setTambahGaji(Object[] gajiPekerjaan) {
        int noRecord;
        
        if((noRecord = gajiDefaultTableModel.getRowCount()-1) >= 0) {
            while((((gajiTable.getValueAt(noRecord, 0) == null) || gajiTable.getValueAt (noRecord, 0).equals("")) && (noRecord > 0))){
                noRecord--;
            }
            
            if (!((gajiTable.getValueAt(noRecord, 0) == null) || gajiTable.getValueAt(noRecord, 0).equals(""))){
                noRecord++;
            }
            
            if (noRecord < gajiDefaultTableModel.getRowCount()){
                if((gajiTable.getValueAt(noRecord, 0) == null) || gajiTable.getValueAt(noRecord, 0).equals("")){
                    gajiDefaultTableModel.removeRow(noRecord--);
                }
            } else {
                noRecord--;
            }
        }
        
        gajiDefaultTableModel.insertRow(++noRecord, gajiPekerjaan);
    }
    
    public void clearGajiTable(){
        gajiDefaultTableModel.setRowCount(0);
    }
    
    private void klikKananTabel(java.awt.event.MouseEvent evt) {
        if(evt.isPopupTrigger()) {
            pekerjaanPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }
    
    private void gajiTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gajiTableMouseReleased
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int rowNumber = gajiTable.rowAtPoint( p );
        ListSelectionModel model = gajiTable.getSelectionModel();
        model.setSelectionInterval ( rowNumber, rowNumber );
        
        klikKananTabel(evt);
    }//GEN-LAST:event_gajiTableMouseReleased

    private void jScrollPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseReleased
        // TODO add your handling code here:
        klikKananTabel(evt);    
        
    }//GEN-LAST:event_jScrollPane1MouseReleased

    private void gajiTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gajiTableKeyPressed
        // TODO add your handling code here:
        
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (gajiTable.getSelectedRow() == (gajiTable.getRowCount()-1)){
                if(gajiTable.getSelectedColumn() ==0) {
                    gajiDefaultTableModel.insertRow(gajiDefaultTableModel.getRowCount(), new Object[]{});
                } else {
                    if (gajiTable.getSelectedColumn() == (gajiTable.getColumnCount()-1)){
                        gajiDefaultTableModel.insertRow(gajiDefaultTableModel.getRowCount(), new Object[]{});
                        gajiTable.changeSelection(gajiTable.getSelectedRow(), 0, false, false);
                } else {
                        gajiTable.changeSelection(gajiTable.getSelectedRow()-1, gajiTable.getSelectedColumn()+1, false, false);
                    }       
                }
            } else {
                if (gajiTable.getSelectedColumn() == (gajiTable.getColumnCount()-1)){
                   gajiTable.changeSelection(gajiTable.getSelectedRow(), 0, false, false);
                } else {
                    gajiTable.setColumnSelectionInterval(gajiTable.getSelectedColumn()+1, gajiTable.getSelectedColumn()+1);
                    gajiTable.setRowSelectionInterval(gajiTable.getSelectedRow()-1, gajiTable.getSelectedRow()-1);
                }
            } 
        }   
    }//GEN-LAST:event_gajiTableKeyPressed

    private void gajiTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_gajiTablePropertyChange
        // TODO add your handling code here:
        if(gajiTable.getSelectedRowCount()>0) {
            if(gajiTable.getSelectedColumn() == 0){
                String kodePekerjaan = "";
                try{
                    kodePekerjaan = gajiTable.getValueAt (gajiTable.getSelectedRow(), 0).toString();
                } catch (Exception ex) {}
                
                if (!kodePekerjaan.equals("")){
                    gajiController.cariPekerjaan(kodePekerjaan);
                }
            }
        }
        
        
    }//GEN-LAST:event_gajiTablePropertyChange

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        gajiController.simpan(ktpTextField, gajiTable);
        
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void lihatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatButtonActionPerformed
        // TODO add your handling code here:
        gajiController.tampilkanFormLihatKaryawan();        
    }//GEN-LAST:event_lihatButtonActionPerformed

    private void ktpTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ktpTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            gajiController.cariKaryawan(ktpTextField);
        }
    }//GEN-LAST:event_ktpTextFieldKeyPressed

    private void tambahMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMenuItemActionPerformed
        // TODO add your handling code here:
        gajiController.tampilkanFormLihatPekerjaan();
    }//GEN-LAST:event_tambahMenuItemActionPerformed

    private void hapusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusMenuItemActionPerformed
        // TODO add your handling code here:
        if (gajiTable.getSelectedRowCount() > 0) {
            gajiDefaultTableModel.removeRow(gajiTable.getSelectedRow());
        }
    }//GEN-LAST:event_hapusMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gajiLabel;
    private javax.swing.JPanel gajiPanel;
    private javax.swing.JTable gajiTable;
    private javax.swing.JMenuItem hapusMenuItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ktpLabel;
    private javax.swing.JTextField ktpTextField;
    private javax.swing.JButton lihatButton;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JPopupMenu pekerjaanPopupMenu;
    private javax.swing.JLabel ruangLabel;
    private javax.swing.JTextField ruangTextField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JMenuItem tambahMenuItem;
    private javax.swing.JButton tutupButton;
    // End of variables declaration//GEN-END:variables
}
